### ISSUE TITLE
bootstrap.sh fails on OSX

### ISSUE THREAD

**Issue by pkappler** [jleclanche/fireplace#250]
The OSX version of readlink doesn't have a -f switch.  You can use 'stat -f', instead.  I don't have access to a Linux box, but I'm pretty sure it'll work there as well.

**Comment by beheh** [comment]
I'm not sure how we can get `stat` to resolve symlinks, at least I can't get that working here. There's [this discussion](https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac) on Stackoverflow which commentors either recommending a bash-solution using `cd` and `pwd`, a small Python or Perl script or using `greadlink -f` when OSX is detected (this requires Mac users to run `brew install coreutils` though).

What's the preferred solution here?

**Comment by pkappler** [comment]
The script still fails after this patch.  The problem isn't that readlink doesn't exist on OSX, but that it doesn't support the -f switch.

**Comment by jleclanche** [comment]
Can you paste me your `readlink --help`?

**Comment by pkappler** [comment]
There's no --help option, but here's the first section of the man page:

NAME
     readlink, stat -- display file status

SYNOPSIS
     stat [-FLnq] [-f format | -l | -r | -s | -x] [-t timefmt] [file ...]
     readlink [-n] [file ...]

DESCRIPTION
     The stat utility displays information about the file pointed to by file.  Read, write
     or execute permissions of the named file are not required, but all directories listed
     in the path name leading to the file must be searchable.  If no argument is given, stat
     displays information about the file descriptor for standard input.

     When invoked as readlink, only the target of the symbolic link is printed.  If the
     given argument is not a symbolic link, readlink will print nothing and exit with an
     error.

     The information displayed is obtained by calling lstat(2) with the given argument and
     evaluating the returned structure.

**Comment by pkappler** [comment]
Entire man page:
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/readlink.1.html

**Comment by jleclanche** [comment]
I think what I pushed should fix it. It will no longer resolve the full path but that's okay.

**Comment by jleclanche** [comment]
Scratch that, hold on.

**Comment by jleclanche** [comment]
OK, now it should use `stat`.

**Comment by pkappler** [comment]
Sorry to keep re-opening this, but it's still not working for me.  Maybe it's working for you because you have an existing copy of fireplace/fireplace/CardDefs.xml?  For a fresh install that file doesn't exist yet. 
Removing lines 32-34 of bootstrap.sh fixes the problem.  Why are those lines necessary?  Is that file ever a symlink?

./bootstrap
Fetching data files from https://github.com/HearthSim/hs-data.git
Cloning into './scripts/hs-data'...
remote: Counting objects: 25, done.        
remote: Compressing objects: 100% (25/25), done.        
remote: Total 25 (delta 2), reused 18 (delta 0), pack-reused 0        
Unpacking objects: 100% (25/25), done.
Checking connectivity... done.
readlink: illegal option -- f
usage: readlink [-n] [file ...]
stat: ./scripts/../fireplace/CardDefs.xml: stat: No such file or directory

**Comment by jleclanche** [comment]
No problem, I just have no way to test so I'm going in blind. The lines are there to ensure the printed path is absolute, but it was silly to do that in shell. Fixed for good now i think.
